; Dự án PlatformIO cho ESP32 (chạy mô phỏng bằng tiện ích Wokwi trong VS Code)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    beegee-tokyo/DHT sensor library for ESPx
    knolleary/PubSubClient
